apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wujvm6j3e-nodejs
  janus-idp.io/tekton: wujvm6j3e-nodejs
  backstage.io/kubernetes-id: wujvm6j3e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wujvm6j3e-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
