apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wujvm6j3e-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wujvm6j3e-nodejs 
  name: wujvm6j3e-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wujvm6j3e-nodejs 
